fric-frac-laravel/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('admin/index');
});
Route::resource('admin','AdminController');
Route::resource('eventcategory','EventCategoryController');
Route::resource('eventtopic','EventTopicController');
Route::resource('event','EventController');

fric-frac-laravel/app/EventCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventCategory extends Model
{
    protected $fillable = [
        'name'
    ];
}

fric-frac-laravel/app/Http/Controllers/EventCategoryController.php
<?php

namespace App\Http\Controllers;

use App\EventCategory;
use Illuminate\Http\Request;

class EventCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $eventCategory = EventCategory::all();
        return view('eventcategory.index', compact('eventCategory'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('eventcategory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        EventCategory::create($request->all());
        return redirect()->route('eventcategory.index')

            ->with('success', 'EventCategory created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\EventCategory  $eventCategory
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        $where = array('id' => $id);
        $data['eventcategory_info'] = EventCategory::where($where)->first();
        return view('eventcategory.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\EventCategory  $eventCategory
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $where = array('id' => $id);
        $data['eventcategory_info'] = EventCategory::where($where)->first();
        return view('eventcategory.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\EventCategory  $eventCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
        ]);
         
        $update = ['name' => $request->name];
        EventCategory::where('id',$id)->update($update);
   
        return redirect()->route('eventcategory.index')

            ->with('success', 'EventCategory updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\EventCategory  $eventCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        EventCategory::where('id',$id)->delete();
        return redirect()->route('eventcategory.index')

            ->with('success', 'EventCategory deleted successfully.');
    }
}

fric-frac-laravel/resources/views/eventcategory/create.blade.php
@extends('layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Event Category</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('eventcategory.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('eventcategory.store') }}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

fric-frac-laravel/resources/views/eventcategory/edit.blade.php
@extends('layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Event Category</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('eventcategory.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{ route('eventcategory.update', $eventcategory_info->id) }}" method="POST" name="update_EventCategory">
    @csrf
    @method('PATCH')
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" value="{{ $eventcategory_info->name }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

fric-frac-laravel/resources/views/eventcategory/index.blade.php
@extends('layout')
@section('content')
<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 7 CRUD Fric-frac</h2>
            </div>
            <div class="pull-right">
                <h2>Event Category</h2>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th width="100px">Action</th>
            <th width="100px">Action</th>
            <th width="100px">Action</th>
        </tr>
        @foreach ($eventCategory as $item)
        <tr>
            <td>{{ $item->id }}</td>
            <td>{{ $item->name }}</td>
            <td><a href="{{ route('eventcategory.show',$item->id)}}" class="btn btn-info">Show</a></td>
            <td><a href="{{ route('eventcategory.edit',$item->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
            <form action="{{ route('eventcategory.destroy', $item->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger" type="submit">Delete</button>
            </td>
            </form>
        </tr>
        @endforeach
    </table>
    <div class="pull-left">
    <a href="{{ route('admin.index')}}" class="btn btn-info">Back to Admin</a>
    </div>
    <div class="pull-right">
    <a class="btn btn-success" href="{{ route('eventcategory.create') }}"> Create Event Category</a>
    </div>
 @endsection

fric-frac-laravel/resources/views/eventcategory/show.blade.php
@extends('layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Show Event Category</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('eventcategory.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form >
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $eventcategory_info->name }}
            </div>
        </div>
    </div>
</form>
@endsection