fric-frac-laravel/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('admin/index');
});
Route::resource('admin','AdminController');
Route::resource('eventcategory','EventCategoryController');
Route::resource('eventtopic','EventTopicController');
Route::resource('event','EventController');

fric-frac-laravel/app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'name',
        'location',
        'starts',
        'ends',
        'image',
        'description',
        'organisername',
        'organiserdescription',
        'eventcategoryid',
        'eventtopicid',
    ];

}

fric-frac-laravel/app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Event;
use App\EventCategory;
use App\EventTopic;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $event = Event::all();
        return view('event.index', compact('event'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $eventTopic = EventTopic::all();
        $eventCategory = EventCategory::all();
        return view('event.create',compact('eventTopic','eventCategory'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'location' => 'required',
            'starts' => 'required',
            'ends' => 'required',
            'image' => 'required',
            'description' => 'required',
            'organisername' => 'required',
            'organiserdescription' => 'required',
            'eventcategoryid' => 'required',
            'eventtopicid' => 'required',
        ]);
        Event::create($request->all());

        return redirect()->route('event.index')

            ->with('success', 'Event created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $where = array('id' => $id);
        $data['event_info'] = Event::where($where)->first();
        return view('event.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $where = array('id' => $id);
        $event_info = Event::where($where)->first();
        $eventcategory_info = EventCategory::all();
        $eventtopic_info = EventTopic::all();
        return view('event.edit', compact('event_info','eventcategory_info','eventtopic_info'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'location' => 'required',
            'starts' => 'required',
            'ends' => 'required',
            'image' => 'required',
            'description' => 'required',
            'organisername' => 'required',
            'organiserdescription' => 'required',
            'eventcategoryid' => 'required',
            'eventtopicid' => 'required',
        ]);
         
        $update = ['name' => $request->name];
        $updatelocation = ['location' => $request->location];
        $updatestarts = ['starts' => $request->starts];
        $updateends = ['ends' => $request->ends];
        $updateimage = ['image' => $request->image];
        $updatedescription = ['description' => $request->description];
        $updateorganisername = ['organisername' => $request->organisername];
        $updatorganiserdescription = ['organiserdescription' => $request->organiserdescription];
        $updateeventcategoryid = ['eventcategoryid' => $request->eventcategoryid];
        $updateeventtopicid = ['eventtopicid' => $request->eventtopicid];
        Event::where('id',$id)->update($update);
        Event::where('id',$id)->update($updatelocation);
        Event::where('id',$id)->update($updatestarts);
        Event::where('id',$id)->update($updateends);
        Event::where('id',$id)->update($updateimage);
        Event::where('id',$id)->update($updatedescription);
        Event::where('id',$id)->update($updateorganisername);
        Event::where('id',$id)->update($updatorganiserdescription);
        Event::where('id',$id)->update($updateeventcategoryid);
        Event::where('id',$id)->update($updateeventtopicid);
        return redirect()->route('event.index')

            ->with('success', 'event updated successfully.');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Event  $event
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        Event::where('id',$id)->delete();
        return redirect()->route('event.index')

            ->with('success', 'Event deleted successfully.');
    }
}

fric-frac-laravel/resources/views/event/create.blade.php
@extends('layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Event</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('event.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('event.store') }}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
            <div class="form-group">
                <strong>Location:</strong>
                <input type="text" name="location" class="form-control" placeholder="Location">
            </div>
            <div class="form-group">
                <strong>Starts:</strong>
                <input type="datetime-local" name="starts" class="form-control">
            </div>
            <div class="form-group">
                <strong>Ends:</strong>
                <input type="datetime-local" name="ends" class="form-control">
            </div>
            <div class="form-group">
                <strong>Image:</strong>
                <input type="text" name="image" class="form-control">
            </div>
            <div class="form-group">
                <strong>Description:</strong>
                <input type="text" name="description" class="form-control" placeholder="Description">
            </div>
            <div class="form-group">
                <strong>Organiser Name:</strong>
                <input type="text" name="organisername" class="form-control" placeholder="Organiser Name">
            </div>
            <div class="form-group">
                <strong>Organiser Description:</strong>
                <input type="text" name="organiserdescription" class="form-control" placeholder="Organiser Description">
            </div>
            <div class="form-group">
            <label for="eventcategoryid">
                <strong>EventCategoryId:</strong>
            </label>
                <select name="eventcategoryid" id="eventcategoryid" class="form-control">
                @foreach($eventCategory as $eventCategory)
                    <option value="{{ $eventCategory->id }}">{{ $eventCategory->id }}</option>
                @endforeach
                </select>
            </div>
            <div class="form-group">
                <strong>EventTopicId:</strong>
                <select name="eventtopicid" id="eventtopicid" class="form-control">
                @foreach($eventTopic as $eventTopic)
                    <option value="{{ $eventTopic->id }}">{{ $eventTopic->id }}</option>
                @endforeach
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

fric-frac-laravel/resources/views/event/edit.blade.php
@extends('layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Event</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('event.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form action="{{ route('event.update', $event_info->id) }}" method="POST" name="update_Event">
    @csrf
    @method('PATCH')
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" value="{{ $event_info->name }}">
            </div>
            <div class="form-group">
                <strong>Location:</strong>
                <input type="text" name="location" class="form-control" value="{{ $event_info->location }}">
            </div>
            <div class="form-group">
                <strong>Starts:</strong>
                <input type="text" name="starts" class="form-control" value="{{ $event_info->starts }}">
            </div>
            <div class="form-group">
                <strong>Ends:</strong>
                <input type="text" name="ends" class="form-control" value="{{ $event_info->ends }}">
            </div>
            <div class="form-group">
                <strong>Image:</strong>
                <input type="text" name="image" class="form-control" value="{{ $event_info->image }}">
            </div>
            <div class="form-group">
                <strong>Description:</strong>
                <input type="text" name="description" class="form-control" placeholder="Description" value="{{ $event_info->description }}">
            </div>
            <div class="form-group">
                <strong>Organiser Name:</strong>
                <input type="text" name="organisername" class="form-control" placeholder="Organiser Name" value="{{ $event_info->organisername }}">
            </div>
            <div class="form-group">
                <strong>Organiser Description:</strong>
                <input type="text" name="organiserdescription" class="form-control" placeholder="Organiser Description" value="{{ $event_info->organiserdescription }}">
            </div>
            <div class="form-group">
                <strong>EventCategoryId:</strong>
                <select name="eventcategoryid" class="form-control" value="{{ $event_info->eventcategoryid }}">
                @foreach($eventcategory_info as $eventcategory_info)
                    <option value="{{ $eventcategory_info->id }}">{{ $eventcategory_info->id }}</option>
                @endforeach
                </select>
            </div>
            <div class="form-group">
                <strong>EventTopicId:</strong>
                <select name="eventtopicid" class="form-control" value="{{ $event_info->eventtopicid }}">
                @foreach($eventtopic_info as $eventtopic_info)
                    <option value="{{ $eventtopic_info->id }}">{{ $eventtopic_info->id }}</option>
                @endforeach
                </select>           
            </div>
        </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

fric-frac-laravel/resources/views/event/index.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 7 CRUD Fric-frac</h2>
            </div>
            <div class="pull-right">
                <h2>Event</h2>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th width="100px">Action</th>
            <th width="100px">Action</th>
            <th width="100px">Action</th>
        </tr>
        @foreach ($event as $item)
        <tr>
            <td>{{ $item->id }}</td>
            <td>{{ $item->name }}</td>
            <td><a href="{{ route('event.show',$item->id)}}" class="btn btn-info">Show</a></td>
            <td><a href="{{ route('event.edit',$item->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
            <form action="{{ route('event.destroy', $item->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger" type="submit">Delete</button>
            </td>
            </form>
        </tr>
        @endforeach
    </table>
    <div class="pull-left">
    <a href="{{ route('admin.index')}}" class="btn btn-info">Back to Admin</a>
    </div>
    <div class="pull-right">
    <a class="btn btn-success" href="{{ route('event.create') }}"> Create Event</a>
    </div>
 @endsection

fric-frac-laravel/resources/views/event/show.blade.php
@extends('layout')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Show Event</h2>
       </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('event.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<form >
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $event_info->name }}
            </div>
            <div class="form-group">
                <strong>Location:</strong>
                {{ $event_info->location }}
            </div>
            <div class="form-group">
                <strong>Starts:</strong>
                {{ $event_info->starts }}
            </div>
            <div class="form-group">
                <strong>Ends:</strong>
                {{ $event_info->ends }}
            </div>
            <div class="form-group">
                <strong>Image:</strong>
                {{ $event_info->image }}
            </div>
            <div class="form-group">
                <strong>Description:</strong>
                {{ $event_info->description }}
            </div>
            <div class="form-group">
                <strong>Organiser Name:</strong>
                {{ $event_info->organisername }}
            </div>
            <div class="form-group">
                <strong>Organiser Description:</strong>
                {{ $event_info->organiserdescription }}
            </div>
            <div class="form-group">
                <strong>EventCategoryId:</strong>
                {{ $event_info->eventcategoryid }}
            </div>
            <div class="form-group">
                <strong>EventTopicId:</strong>
                {{ $event_info->eventtopicid }}
            </div>
        </div>
    </div>
</form>
@endsection